import type { MosqueRecord } from "@/types/mosque";

export const DEMO_CITY = {
  label: "Birmingham city centre",
  latitude: 52.4862,
  longitude: -1.8904,
};

export const demoMosques: MosqueRecord[] = [
  {
    id: "mosque-1",
    name: "Green Lane Masjid",
    latitude: 52.4655,
    longitude: -1.8523,
    address: "20 Green Lane, Small Heath, Birmingham",
    qrToken: "green-lane-masjid",
    prayers: {
      fajr: "05:15",
      zuhr: "13:30",
      asr: "17:10",
      maghrib: "20:34",
      isha: "22:00",
    },
    juma1: "13:15",
    juma2: "14:00",
    remarks: "Women section available. Limited parking near the side entrance.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    isVerified: true,
    images: [
      {
        id: "img-1",
        mosqueId: "mosque-1",
        imageUrl:
          "https://images.unsplash.com/photo-1512632578888-169bbbc64f33?auto=format&fit=crop&w=900&q=80",
        type: "entrance",
      },
    ],
  },
  {
    id: "mosque-2",
    name: "Birmingham Central Mosque",
    latitude: 52.4706,
    longitude: -1.8853,
    address: "180 Belgrave Middleway, Birmingham",
    qrToken: "birmingham-central-mosque",
    prayers: {
      fajr: "05:20",
      zuhr: "13:25",
      asr: "17:05",
      maghrib: "20:32",
      isha: "21:55",
    },
    juma1: "13:30",
    juma2: "14:15",
    remarks: "Second jamaat available. Large prayer hall for travelers.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    isVerified: true,
    images: [
      {
        id: "img-2",
        mosqueId: "mosque-2",
        imageUrl:
          "https://images.unsplash.com/photo-1564769662533-4f00a87b4056?auto=format&fit=crop&w=900&q=80",
        type: "parking",
      },
    ],
  },
  {
    id: "mosque-3",
    name: "Sparkbrook Islamic Centre",
    latitude: 52.4552,
    longitude: -1.8786,
    address: "155 Stratford Road, Sparkbrook, Birmingham",
    qrToken: "sparkbrook-islamic-centre",
    prayers: {
      fajr: "05:10",
      zuhr: "13:20",
      asr: "17:00",
      maghrib: "20:30",
      isha: "21:50",
    },
    juma1: "13:00",
    remarks: "Wudu area recently refurbished.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    isVerified: false,
    images: [],
  },
  {
    id: "mosque-4",
    name: "Aston Masjid",
    latitude: 52.5007,
    longitude: -1.8864,
    address: "Aston Hall Road, Aston, Birmingham",
    qrToken: "aston-masjid",
    prayers: {
      fajr: "05:18",
      zuhr: "13:35",
      asr: "17:18",
      maghrib: "20:36",
      isha: "22:03",
    },
    juma1: "13:20",
    juma2: "14:10",
    remarks: "Good motorway access for route stops.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    isVerified: true,
    images: [],
  },
  {
    id: "mosque-5",
    name: "West Bromwich Masjid",
    latitude: 52.5178,
    longitude: -1.9946,
    address: "32 High Street, West Bromwich",
    qrToken: "west-bromwich-masjid",
    prayers: {
      fajr: "05:25",
      zuhr: "13:28",
      asr: "17:14",
      maghrib: "20:35",
      isha: "22:01",
    },
    juma1: "13:10",
    juma2: null,
    remarks: "Short walk from the main road. Family room available.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
    isVerified: false,
    images: [],
  },
  {
    id: "mosque-6",
    name: "Solihull Prayer Centre",
    latitude: 52.4118,
    longitude: -1.7776,
    address: "Station Road, Solihull",
    qrToken: "solihull-prayer-centre",
    prayers: {
      fajr: "05:12",
      zuhr: "13:22",
      asr: "17:08",
      maghrib: "20:31",
      isha: "21:54",
    },
    juma1: "13:15",
    juma2: "13:55",
    remarks: "Ideal for airport and M42 routes.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    isVerified: true,
    images: [],
  },
  {
    id: "mosque-7",
    name: "Walsall Masjid Al-Falah",
    latitude: 52.5862,
    longitude: -1.9822,
    address: "Palfrey, Walsall",
    qrToken: "walsall-masjid-al-falah",
    prayers: {
      fajr: "05:28",
      zuhr: "13:33",
      asr: "17:16",
      maghrib: "20:37",
      isha: "22:04",
    },
    juma1: "13:30",
    remarks: "Parking fills up quickly on Fridays.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
    isVerified: false,
    images: [],
  },
  {
    id: "mosque-8",
    name: "Coventry Road Musalla",
    latitude: 52.4709,
    longitude: -1.8263,
    address: "Coventry Road, Birmingham",
    qrToken: "coventry-road-musalla",
    prayers: {
      fajr: "05:14",
      zuhr: "13:24",
      asr: "17:09",
      maghrib: "20:33",
      isha: "21:58",
    },
    juma1: "13:05",
    juma2: null,
    remarks: "Quick stop location close to the ring road.",
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    isVerified: true,
    images: [],
  },
];
