export interface FlightAirport {
  code: string;
  city: string;
  country: string;
  timezoneOffsetHours: number;
  prayerSpace: string;
  nearestMasjid: string;
  nearestMasjidTravel: string;
}

export const FLIGHT_AIRPORTS: FlightAirport[] = [
  {
    code: "BOM",
    city: "Mumbai",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Terminal prayer room available near departures.",
    nearestMasjid: "Masjid-e-Ibrahim (Sahar area)",
    nearestMasjidTravel: "~12 to 18 min by cab",
  },
  {
    code: "DEL",
    city: "Delhi",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer rooms available in selected terminal zones.",
    nearestMasjid: "Jama Masjid, Old Delhi",
    nearestMasjidTravel: "~45 to 60 min by cab",
  },
  {
    code: "HYD",
    city: "Hyderabad",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Multi-faith prayer hall available.",
    nearestMasjid: "Masjid near Shamshabad market area",
    nearestMasjidTravel: "~15 to 20 min by cab",
  },
  {
    code: "BLR",
    city: "Bengaluru",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Quiet prayer area available inside terminal.",
    nearestMasjid: "Masjid near Devanahalli town",
    nearestMasjidTravel: "~20 to 25 min by cab",
  },
  {
    code: "CCU",
    city: "Kolkata",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer room available in terminal facilities.",
    nearestMasjid: "Masjid near Kaikhali and airport approach",
    nearestMasjidTravel: "~15 to 25 min by cab",
  },
  {
    code: "MAA",
    city: "Chennai",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Multi-faith prayer room available in terminal area.",
    nearestMasjid: "Pallavaram/Meenambakkam area mosques",
    nearestMasjidTravel: "~12 to 20 min by cab",
  },
  {
    code: "AMD",
    city: "Ahmedabad",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Quiet prayer corner available near departures.",
    nearestMasjid: "Airport road and Shahibaug area masjids",
    nearestMasjidTravel: "~15 to 25 min by cab",
  },
  {
    code: "COK",
    city: "Kochi",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer room available in terminal complex.",
    nearestMasjid: "Nedumbassery area mosques",
    nearestMasjidTravel: "~10 to 18 min by cab",
  },
  {
    code: "GOI",
    city: "Goa",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer room available depending on terminal section.",
    nearestMasjid: "Vasco and surrounding local masjids",
    nearestMasjidTravel: "~15 to 30 min by cab",
  },
  {
    code: "PNQ",
    city: "Pune",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer space available inside terminal.",
    nearestMasjid: "Viman Nagar and Yerwada area mosques",
    nearestMasjidTravel: "~15 to 25 min by cab",
  },
  {
    code: "LKO",
    city: "Lucknow",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer room available in terminal premises.",
    nearestMasjid: "Amausi and nearby city-route mosques",
    nearestMasjidTravel: "~15 to 25 min by cab",
  },
  {
    code: "TRV",
    city: "Thiruvananthapuram",
    country: "India",
    timezoneOffsetHours: 5.5,
    prayerSpace: "Prayer facilities available at terminal.",
    nearestMasjid: "Airport locality mosques",
    nearestMasjidTravel: "~10 to 18 min by cab",
  },
  {
    code: "JED",
    city: "Jeddah",
    country: "Saudi Arabia",
    timezoneOffsetHours: 3,
    prayerSpace: "Dedicated musalla spaces across terminals.",
    nearestMasjid: "Mosques available around airport perimeter",
    nearestMasjidTravel: "~8 to 15 min by cab",
  },
  {
    code: "DXB",
    city: "Dubai",
    country: "UAE",
    timezoneOffsetHours: 4,
    prayerSpace: "Prayer rooms distributed across all terminals.",
    nearestMasjid: "Airport-area neighborhood masjids",
    nearestMasjidTravel: "~10 to 20 min by cab",
  },
  {
    code: "AUH",
    city: "Abu Dhabi",
    country: "UAE",
    timezoneOffsetHours: 4,
    prayerSpace: "Prayer spaces and ablution facilities available.",
    nearestMasjid: "Masjid near airport road communities",
    nearestMasjidTravel: "~10 to 18 min by cab",
  },
  {
    code: "IST",
    city: "Istanbul",
    country: "Turkey",
    timezoneOffsetHours: 3,
    prayerSpace: "Multiple masjid/prayer areas inside airport.",
    nearestMasjid: "Airport campus mosques",
    nearestMasjidTravel: "Inside/near terminal area",
  },
  {
    code: "LHR",
    city: "London",
    country: "United Kingdom",
    timezoneOffsetHours: 1,
    prayerSpace: "Interfaith prayer rooms at major terminals.",
    nearestMasjid: "Heathrow-area local mosques",
    nearestMasjidTravel: "~15 to 25 min by transit/cab",
  },
  {
    code: "MAN",
    city: "Manchester",
    country: "United Kingdom",
    timezoneOffsetHours: 1,
    prayerSpace: "Interfaith prayer room available within terminal zones.",
    nearestMasjid: "South Manchester community mosques",
    nearestMasjidTravel: "~20 to 35 min by transit/cab",
  },
  {
    code: "JFK",
    city: "New York",
    country: "United States",
    timezoneOffsetHours: -4,
    prayerSpace: "Multi-faith chapels and prayer spaces in terminals.",
    nearestMasjid: "Jamaica/Queens community mosques",
    nearestMasjidTravel: "~20 to 35 min by cab",
  },
  {
    code: "EWR",
    city: "Newark",
    country: "United States",
    timezoneOffsetHours: -4,
    prayerSpace: "Multi-faith prayer rooms available in terminals.",
    nearestMasjid: "Newark/Jersey City area mosques",
    nearestMasjidTravel: "~20 to 35 min by cab",
  },
  {
    code: "IAD",
    city: "Washington",
    country: "United States",
    timezoneOffsetHours: -4,
    prayerSpace: "Interfaith chapels and quiet prayer areas available.",
    nearestMasjid: "Dulles corridor area mosques",
    nearestMasjidTravel: "~20 to 35 min by cab",
  },
  {
    code: "YYZ",
    city: "Toronto",
    country: "Canada",
    timezoneOffsetHours: -4,
    prayerSpace: "Prayer room available in terminal facilities.",
    nearestMasjid: "Mississauga/Toronto area mosques",
    nearestMasjidTravel: "~20 to 35 min by cab",
  },
  {
    code: "YVR",
    city: "Vancouver",
    country: "Canada",
    timezoneOffsetHours: -7,
    prayerSpace: "Prayer room available inside terminal.",
    nearestMasjid: "Richmond and Vancouver area mosques",
    nearestMasjidTravel: "~20 to 35 min by cab",
  },
  {
    code: "SIN",
    city: "Singapore",
    country: "Singapore",
    timezoneOffsetHours: 8,
    prayerSpace: "Muslim prayer rooms available in terminals.",
    nearestMasjid: "Masjid around Changi vicinity",
    nearestMasjidTravel: "~12 to 20 min by cab",
  },
  {
    code: "KUL",
    city: "Kuala Lumpur",
    country: "Malaysia",
    timezoneOffsetHours: 8,
    prayerSpace: "Musolla facilities widely available across terminals.",
    nearestMasjid: "KLIA area mosques",
    nearestMasjidTravel: "~10 to 18 min by cab",
  },
  {
    code: "DOH",
    city: "Doha",
    country: "Qatar",
    timezoneOffsetHours: 3,
    prayerSpace: "Dedicated prayer rooms available throughout terminal.",
    nearestMasjid: "Airport vicinity masjids",
    nearestMasjidTravel: "~10 to 20 min by cab",
  },
  {
    code: "MCT",
    city: "Muscat",
    country: "Oman",
    timezoneOffsetHours: 4,
    prayerSpace: "Prayer spaces available in terminal sections.",
    nearestMasjid: "Seeb and airport road mosques",
    nearestMasjidTravel: "~10 to 20 min by cab",
  },
];

export function getAirportByCode(code: string) {
  const normalized = code.trim().toUpperCase();
  return FLIGHT_AIRPORTS.find((airport) => airport.code === normalized) || null;
}

export const FLIGHT_AIRPORT_CODES = FLIGHT_AIRPORTS.map((airport) => airport.code);
